### ISSUE TITLE
fail2ban AND sipban incompatibility ?

### ISSUE THREAD

**Issue by Rico29** [elpop/sipban#2] opened 2020-11-12 07:57 UTC
Hello,
I'm using fail2ban and sipban for asterisk on a server.

Fail2ban works fine, but sipban, when starting, does not put it's "$ipt -t filter -I INPUT -p udp --dport 5060 -j $Config{'iptables.chain'}" rule in INPUT chain.
So I have , when doing iptables -L -nv :+1: 

```
Chain INPUT (policy ACCEPT 805K packets, 149M bytes)
 pkts bytes target     prot opt in     out     source               destination         
20688   11M f2b-asterisk-udp  udp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 5060
    0     0 f2b-asterisk-tcp  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            multiport dports 5060
```
chain "sipban-udp" is correctly created :

```
Chain sipban-udp (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 REJECT     all  --  *      *       54.36.166.196        0.0.0.0/0            reject-with icmp-port-unreachable
    0     0 REJECT     all  --  *      *       62.4.14.74           0.0.0.0/0            reject-with icmp-port-unreachable
    0     0 REJECT     all  --  *      *       80.94.93.3           0.0.0.0/0            reject-with icmp-port-unreachable
    0     0 REJECT     all  --  *      *       80.94.93.32          0.0.0.0/0            reject-with icmp-port-unreachable
    0     0 REJECT     all  --  *      *       37.120.155.138       0.0.0.0/0            reject-with icmp-port-unreachable
    0     0 REJECT     all  --  *      *       40.76.244.210        0.0.0.0/0            reject-with icmp-port-unreachable
    0     0 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0  
```

I'm going to do more tests in the morning.
Regards

**Comment by elpop** [comment] 2020-11-13 03:54
What linux  and distribution version is this machine?

**Comment by Rico29** [comment] 2020-11-13 07:35
Hello @elpop 
debian 10.6
fail2ban 0.10.2-2.1

I was not able to reproduce that on another host on same versions...

**Comment by elpop** [comment] 2020-11-14 03:35
the server has installed "ufw"? (the Debian firewall utility), seems like another software take precedence. I test sipban on Centos and Ubuntu without problem, even with f2b installed.

**Comment by Rico29** [comment] 2020-11-16 10:57
hello.
nope, there is no other firewall soft installed :(

**Comment by elpop** [comment] 2020-11-30 04:45
I can't reproduce the issue, I close this case until we find a way to reproduce the problem

**Closed as completed by elpop** 2020-11-30 04:45 UTC
